### PR TITLE
Added Data Functionality

### PR DESCRIPTION
**Pull request by Ronak1605**
### Description
Added functionality to perform CRUD operations on the data, tested using postman.

### Test Example
Screenshot 2024-08-18 at 7 52 13 PM
Screenshot 2024-08-18 at 7 53 16 PM

### Notes
Make sure to delete all recipes once done testing.

### CODE REVIEW

**Comment by Ronak1605** [comment]
Will make changes to pass the sonar and link to a database connected to our group account.

**Comment by Ronak1605** [comment]
### Summary
Fixed sonar code smells and connected to database linked to the group email so everybody can see the database state.

### Notes
You can view the database state by visiting mongoDB Atlas and signing in with the group email. Once logged in you should see something similar to the image below.
Screenshot 2024-08-19 at 10 33 43 PM


Click 'Browse collections' and you should see the current DB state as shown in the image below.
Screenshot 2024-08-19 at 10 35 31 PM

**Review by js773er — APPROVED** [review]
lgtm

**Comment by rtal831** [comment]
lgtm

**Pull request merged**
