### PR TITLE
Feat search bar

### LINKED ISSUE #9: Implement Results Page

### LINKED ISSUE #23: Header Bar

### PR DESCRIPTION
**Pull request by js773er**
# Description

Added a search bar along with advanced search options, including meal type, serving size, and cuisine.
Stored the client-side API route in frontend/lib/api.js.
Example: Searching for "beef avocado" with meal type set to "dinner," serving size set to "2," and cuisine set to "any" should output 5-10 recipes.

Screenshot 2024-08-20 at 9 50 54 PM

# Notes:

There seems to be an issue with the **/generate** route when generating multiple(above 5) recipes and calling Pexels for images. This sometimes causes errors and a long waiting time.
I added a new route at **http://localhost:5000/api/recipes/only** specifically for generating recipes without images. This route includes an additional field in the response called **detailedIngredients**, which can be used on the recipe detail page, while the **ingredients** field is intended for display on the result list page.

I recommend adding a new API route specifically for generating images when given an image name and the route would be called only when the "View" button is clicked on the result recipe list.

response

In Nextjs 14,Each subdirectory under the App directory corresponds to a unique route in the application.
Example: App/result/page.js corresponds to the /result route.
more information: https://nextjs.org/docs/app/api-reference/functions/use-router

### CODE REVIEW

**Comment by SOFTENG-310-Group-7** [comment]
Currently running into some errors while running this:

Seems like the recipe does not generate at the endpoint, tried to send some postman post requests to the endpoint but it isn't generating:
test

This is what the console says:
test2

Error seems to be with the generate recipe method

**Comment by js773er** [comment]
> Currently running into some errors while running this:
> 
> 
> 
> Seems like the recipe does not generate at the endpoint, tried to send some postman post requests to the endpoint but it isn't generating:
> 
> test
> 
> 
> 
> This is what the console says:
> 
> test2
> 
> 
> 
> Error seems to be with the generate recipe method
> 
> 
> 
> 

did u add Gemini api key?

**Comment by js773er** [comment]
> Currently running into some errors while running this:
> 
> 
> 
> Seems like the recipe does not generate at the endpoint, tried to send some postman post requests to the endpoint but it isn't generating:
> 
> test
> 
> 
> 
> This is what the console says:
> 
> test2
> 
> 
> 
> Error seems to be with the generate recipe method
> 
> 
> 
> 

Also make sure to pull as I made some changes

**Comment by SOFTENG-310-Group-7** [comment]
Sweet did a pull and its working now,

sometimes the generation of a recipe fails, throwing the same error that I had before but a large majority of the time it works so all good for now

Sonar checks are of low and minor priority so alg to pass with those

Happy to merge this in!

**Review by SOFTENG-310-Group-7 — APPROVED** [review]
lgtm

**Pull request merged**
