### PR TITLE
Feat next setup

### LINKED ISSUE #15: Set up frontend

### PR DESCRIPTION
**Pull request by js773er**
Set up the initial Next application structure with TailwindCSS. Configured basic settings and dependencies.
Implemented default styling and layout.

### CODE REVIEW

**Comment by hayley9080** [comment]
Hey I've just had a look, would you be able to sync your fork with Reece's most recent pr? There might be a couple conflicts with that and this one :)

**Comment by js773er** [comment]
> Hey I've just had a look, would you be able to sync your fork with Reece's most recent pr? There might be a couple conflicts with that and this one :)

I'll get this done today.

**Comment by js773er** [comment]
I've added current api route and layout to next client side.

**Comment by Ronak1605** [comment]
Looks good!

**Pull request merged**
