### PR TITLE
Recipe results page

### PR DESCRIPTION
**Pull request by rtal831**
Addressed issue #10 

Uses NextUI cards - remember to run npm install to get dependencies

To see the page: run the backend and frontend then go to localhost:3000/recipe-result

### CODE REVIEW

**Comment by hayley9080** [comment]
Looks good! Would be great if you'd be able to add the other fields that are in the database model like `title, ingredients, cookingTime, instructions, and recipeImage` to the function so that it stays consistent with the data from the backend. Theres a schema under models -> Recipe.js that has this. I would also recommend maybe looking into splitting up the page into separate components so that the code is more reusable - but its not a super big priority right now. 
There are also some libraries with some card components that could be used as well like [NextUI](https://nextui.org/docs/components/card) and [CoreUI](https://coreui.io/react/docs/components/card/) that might be helpful.

**Comment by rtal831** [comment]
will have a look at that now and will try to get something cleaner out

**Comment by rtal831** [comment]
Need to install nextUi stuff to view

**Comment by js773er** [comment]
I think package.json is a dependency file that shouldn’t be removed from the remote Git repository. package-lock.json needs to be removed from the remote tho

**Pull request merged**
