### PR TITLE
Initial Database Setup

### LINKED ISSUE #12: Set Up Database

### PR DESCRIPTION
**Pull request by Ronak1605**
I've implemented the initial database setup with the following functionality: 
- Established a connection with the database
- Made an initial schema model for the database (maybe subject to change as we establish our design decisions)
- Made 'outline' functions for sending and receiving data from the database, functionality to send and receive data needs to be implemented.

For access to the database use the following commands in the terminal:
npm install mongoose
npm install mongodb
npm isntall dotenv

### CODE REVIEW

**Comment by hayley9080** [comment]
I just pulled and ran the backend with no worries, but when running the client I get this error in the browser - `Application error: a client-side exception has occurred (see the browser console for more information).` - do you know what could cause this?
image

**Comment by Ronak1605** [comment]
> I just pulled and ran the backend with no worries, but when running the client I get this error in the browser - `Application error: a client-side exception has occurred (see the browser console for more information).` - do you know what could cause this? image

I'm not receiving those errors when I run it, strange. I'll look into this now.

**Comment by js773er** [comment]
Anyone merge this pull request please use Squash and merge option in the drop down.

**Comment by Ronak1605** [comment]
It should work now, I'm receiving no errors when inputting data and its appearing in the server. Let me know if it works on your end. 
Screenshot 2024-08-15 at 10 28 01 PM
Screenshot 2024-08-15 at 10 28 06 PM

**Review by hayley9080 — APPROVED** [review]
yep all is working on my end now :)

**Pull request merged**
